if ( GetLocale() == "zhCN" ) then
_G["BINDING_HEADER_TOTEMTIMERSHEADER"] = "图腾助手按键绑定"
_G["BINDING_NAME_TOTEMTIMERSAIR"] = "施放当前风系图腾"
_G["BINDING_NAME_TOTEMTIMERSAIRMENU"] = "打开风系图腾按钮"
_G["BINDING_NAME_TOTEMTIMERSEARTH"] = "施放当前土系图腾"
_G["BINDING_NAME_TOTEMTIMERSEARTHMENU"] = "打开土系图腾按钮"
_G["BINDING_NAME_TOTEMTIMERSEARTHSHIELDLEFT"] = "大地之盾左键点击"
_G["BINDING_NAME_TOTEMTIMERSEARTHSHIELDMIDDLE"] = "大地之盾中间点击"
_G["BINDING_NAME_TOTEMTIMERSEARTHSHIELDRIGHT"] = "大地之盾右键点击"
_G["BINDING_NAME_TOTEMTIMERSFIRE"] = "施放当前火系图腾"
_G["BINDING_NAME_TOTEMTIMERSFIREMENU"] = "打开火系图腾按钮"
_G["BINDING_NAME_TOTEMTIMERSWATER"] = "施放当前水系图腾"
_G["BINDING_NAME_TOTEMTIMERSWATERMENU"] = "打开水系图腾按钮"
_G["BINDING_NAME_TOTEMTIMERSWEAPONBUFF1"] = "武器buff 1"
_G["BINDING_NAME_TOTEMTIMERSWEAPONBUFF2"] = "武器buff 2"



end


local L = LibStub("AceLocale-3.0"):NewLocale("TotemTimers", "zhCN")
if not L then return end
L["Stormstrike"] = "风暴打击"
L["Lava Lash"] = "熔岩猛击"
L["Earth Shock"] = "地震术"
L["Totemic Call"] = "召唤图腾"
L["Water Shield"] = "水之护盾"
L["Air Button"] = "空气图腾"
L["Cooldown"] = "冷却"
L["Ctrl-Leftclick to remove weapon buffs"] = "Ctrl-左键点击删除武器增益"
L["Delete Set"] = "删除图腾设置 %u?"
L["Earth Button"] = "大地图腾"
L["Fire Button"] = "火焰图腾"
L["Leftclick to cast %s"] = "左键点击施放 %s"
L["Leftclick to cast spell"] = "左键点击施放法术"
L["Leftclick to load totem set"] = "左键点击加载图腾设置 %s"
L["Leftclick to open totem set menu"] = "左键打开设置界面"
L["Long Cooldown"] = "长时间冷却"
L["Maelstrom Notifier"] = "漩涡武器就绪!"
L["Middleclick to cast %s"] = "中键点击施放 %s"
L["Next leftclick casts %s"] = "下一个左键点击施放 %s"
L["Reset"] = "重置图腾计时器!"
L["Rightclick to assign both %s and %s to leftclick"] = "和 %s 和 %s 都到左键点击"
L["Rightclick to assign spell to leftclick"] = "右键点击指定法术到左键点击"
L["Rightclick to assign totem to timer button"] = "右键点击指定图腾到计时器."
L["Rightclick to cast %s"] = "右键点击施放 %s"
L["Rightclick to delete totem set"] = "右键删除图腾设置"
L["Rightclick to save active totem configuration as set"] = "右键保存激活的图腾设置"
L["Shield removed"] = "%s 效果消失"
L["Shift-Rightclick to assign spell to middleclick"] = "Shift-右键点击分配法术到中键点击"
L["Shift-Rightclick to assign spell to rightclick"] = "Shift-右键点击分配法术到右键点击"
L["Totem Destroyed"] = "%s 被摧毁了"
L["Totem Expired"] = "%s 到期了"
L["Totem Expiring"] = "%s 即将到期"
L["Water Button"] = "水之图腾"
